// <auto-generated />
using System;
using Discount.Grpc.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Discount.Grpc.Migrations
{
    [DbContext(typeof(DiscountContext))]
    partial class DiscountContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Discount.Grpc.Data.Discount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Discount");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6f1c0f77-8f45-4a84-9fc7-1e7a6bb7e101"),
                            Amount = 150m,
                            Description = "IPhone1 Discount",
                            ProductId = new Guid("3d13c704-e34e-441b-bd29-6037bda6ae67"),
                            ProductName = "Iphone 1"
                        },
                        new
                        {
                            Id = new Guid("8a4d2c91-1b7e-4f56-a3c8-9d0e2f7b6a42"),
                            Amount = 78m,
                            Description = "Samsung1 Discount",
                            ProductId = new Guid("12ff1742-8097-4f95-a2ba-9289605a09f3"),
                            ProductName = "Samung Galaxy 1"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
